In [3]:
import torch
import torch.nn as nn

# 2个神经元的输出y的数值为
y = torch.randn(2)
print(y)
m = nn.Softmax(dim=0)
out = m(y)
print(out)

tensor([-0.5785,  0.4919])
tensor([0.2553, 0.7447])


In [5]:
x = torch.randint(0, 255, (1, 128*128), dtype=torch.float32)
fc = nn.Linear(128*128, 2)
y = fc(x)
print(y)
# 注意y的shape是(1, 2)
output = nn.Softmax(dim=1)(y)
print(output)

tensor([[-107.4843,  -10.6156]], grad_fn=<AddmmBackward0>)
tensor([[8.5199e-43, 1.0000e+00]], grad_fn=<SoftmaxBackward0>)
