##### NumPy 数组

1.Python 中的列表可以动态地改变，而 NumPy 数组是不可以的，它在创建时就有固定大小了。改变 Numpy 数组长度的话，会新创建一个新的数组并且删除原数组。
2.NumPy 数组中的数据类型必须是一样的，而列表中的元素可以是多样的。
3.NumPy 针对 NumPy 数组一系列的运算进行了优化，使得其速度特别快，并且相对于 Python 中的列表，同等操作只需使用更少的内存。

把一个列表传入到 np.array() 或 np.asarray() 中创建数组，np.array() 属于深拷贝，np.asarray() 则是浅拷贝
np.ones() 与 np.zeros()
np.arange()
np.linspace()

ndim --> 维度的个数
shape --> 维度
size --> 元素的个数
dtype --> 数据类型（int8、int16、int32、float32、float64），astype() 改变数组的数据类型

数组的轴



In [6]:
import numpy as np
interest_score = np.random.randint(10, size=(4, 3))
print(interest_score)
np.sum(interest_score,axis=0)
np.sum(interest_score,axis=1)

[[2 2 6]
 [4 7 8]
 [6 9 3]
 [5 8 1]]


array([10, 19, 18, 14])

In [9]:
scores = np.random.rand(256, 256, 2)
scores[:,:,1] = 1 - scores[:,:,0]
mask = np.zeros(scores.shape)
mask

result = np.argmax(scores, axis=2)
result


array([[0, 0, 0, ..., 1, 1, 0],
       [1, 1, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [1, 1, 1, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 1, 1],
       [0, 1, 1, ..., 1, 1, 0]])

##### Tensor

创建：torch.tensor(data, dtype=None, device=None,requires_grad=False)
    requires_grad 如果是训练过程就要设置为 true，目的是方便求导、更新参数。而到了验证或者测试过程，我们的目的是检查当前模型的泛化能力，那就要把 requires_grad 设置成 Fasle，避免这个参数根据 loss 自动更新。

tensor的转换
a = torch.tensor(1)
b = a.item()

b = torch.tensor([1, 2, 3])
c = b.numpy().tolist()





In [11]:
import torch

t1 = torch.zeros((3,2),dtype=None)
t1

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [12]:
a = torch.tensor(1)
b = a.item()
b

1

In [13]:
a = torch.zeros(2,3,4)
a

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [17]:
x = torch.rand(2,1,3)
x.shape
y = x.squeeze()
y.shape

torch.Size([2, 1, 3])

In [18]:
A=torch.tensor([1,2,3,4,5,6,7,8,9,10])
B = torch.chunk(A, 2, 0)
B

(tensor([1, 2, 3, 4, 5]), tensor([ 6,  7,  8,  9, 10]))

In [19]:
from torch.utils.data import Dataset

class MyDataset(Dataset):
    def __init__(self, data_tensor, target_tensor):
        self.data_tensor = data_tensor
        self.target_tensor = target_tensor

    def __len__(self):
        return self.data_tensor.size(0)

    def __getitem__(self, index):
        return self.data_tensor[index], self.target_tensor[index]


In [26]:
data_tensor = torch.randn(10,3)
target_tensor = torch.randint(2, (10,))
my_dataset = MyDataset(data_tensor,target_tensor)
data_tensor

tensor([[ 0.6865,  0.4576, -2.0241],
        [ 0.9022, -0.6191, -0.7715],
        [-1.4074, -0.4854,  0.2196],
        [-0.5351,  1.3807,  0.2421],
        [-0.1482,  1.1564, -1.1256],
        [ 0.9680,  0.3446,  0.0744],
        [ 0.1771,  0.8424, -1.5460],
        [ 0.6768, -0.5446,  1.3475],
        [-1.6586,  0.7589, -2.1427],
        [ 1.6918,  0.0735,  0.5188]])

In [27]:
from torch.utils.data import DataLoader

tensor_dataloader = DataLoader(dataset=my_dataset, batch_size=2, shuffle=True, num_workers=0)

for data, target in tensor_dataloader:
    print(data, target)

tensor([[ 1.6918,  0.0735,  0.5188],
        [-0.1482,  1.1564, -1.1256]]) tensor([1, 0])
tensor([[ 0.6768, -0.5446,  1.3475],
        [-1.6586,  0.7589, -2.1427]]) tensor([0, 0])
tensor([[-0.5351,  1.3807,  0.2421],
        [ 0.9022, -0.6191, -0.7715]]) tensor([0, 0])
tensor([[ 0.9680,  0.3446,  0.0744],
        [ 0.6865,  0.4576, -2.0241]]) tensor([1, 1])
tensor([[ 0.1771,  0.8424, -1.5460],
        [-1.4074, -0.4854,  0.2196]]) tensor([0, 1])
