In [1]:
import numpy as np

In [3]:
lst1 = [3.14, 2.17, 0, 1, 2]
nd1 = np.array(lst1)
print(type(nd1),nd1)

<class 'numpy.ndarray'> [3.14 2.17 0.   1.   2.  ]


##### random 生成随机数

In [9]:
nd2 = np.random.random([3,3])
print(nd2, nd2.shape)

np.random.seed(123)
nd3 = np.random.randn(2,3)
print(nd3)
np.random.shuffle(nd3)
print(nd3)

[[0.9807642  0.68482974 0.4809319 ]
 [0.39211752 0.34317802 0.72904971]
 [0.43857224 0.0596779  0.39804426]] (3, 3)
[[-1.0856306   0.99734545  0.2829785 ]
 [-1.50629471 -0.57860025  1.65143654]]
[[-1.50629471 -0.57860025  1.65143654]
 [-1.0856306   0.99734545  0.2829785 ]]


##### 生成特定的矩阵

In [14]:
nd4 = np.zeros((3,4))
nd5 = np.zeros_like(nd4)
nd6 = np.ones((2,3))
nd7 = np.eye(3)
nd8 = np.diag([1,2,3])

print(nd4)
print(nd5)
print(nd6)
print(nd7)
print(nd8)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


##### 保存暂时的数据到本地文件

In [15]:
nd9 = np.random.random([5,5])
np.savetxt(X=nd9, fname='./test1.txt')
nd10 = np.loadtxt('./test1.txt')
print(nd10)

[[0.41092437 0.5796943  0.13995076 0.40101756 0.62731701]
 [0.32415089 0.24475928 0.69475518 0.5939024  0.63179202]
 [0.44025718 0.08372648 0.71233018 0.42786349 0.2977805 ]
 [0.49208478 0.74029639 0.35772892 0.41720995 0.65472131]
 [0.37380143 0.23451288 0.98799529 0.76599595 0.77700444]]


#####  利用arange、linspace函数生成数组

In [32]:
nd11 = np.arange(1,10)
print(nd11)
nd12 = np.linspace(0.1,1,10)
print(nd12)

[1 2 3 4 5 6 7 8 9]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


##### 获取np元素

In [34]:
from numpy import random as nr

In [43]:
np.random.seed(2024)
nd13 = np.arange(1,25,dtype=float)
print(nd13)
c1 = nr.choice(nd13,size=(3,4))
print(c1)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24.]
[[ 9.  1.  1.  5.]
 [24. 10.  2.  4.]
 [11.  3.  1.  6.]]


##### 相乘和点积

In [50]:
A = np.array([[1,2], [-1,4]])
B = np.array([[2,0],[3,4]])
print(A*B)
print(A * 2.0)
print(np.multiply(A, B))

x1 = np.array([[1,2], [3,4]])
x2 = np.array([[5,6,7],[8,9,10]])
x3 = np.dot(x1,x2)
print(x3)

[[ 2  0]
 [-3 16]]
[[ 2.  4.]
 [-2.  8.]]
[[ 2  0]
 [-3 16]]
[[21 24 27]
 [47 54 61]]


##### 数组变形

In [63]:
arr = np.arange(10)
print(arr)
print(arr.reshape(2,5))
print(arr.reshape(5,-1))

arr.resize(2,5)
print(arr)

print(arr.T)

print(arr.ravel())
print(arr.ravel('F'))

print(arr)

print(arr.flatten())

arr.resize(1,10)
print(arr.shape)
print(arr.squeeze().shape)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[0 1 2 3 4 5 6 7 8 9]
[0 5 1 6 2 7 3 8 4 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
(1, 10)
(10,)


##### 合并数组

In [79]:
a= np.array([1,2,3])
b = np.array([4,5,6])
print(np.append(a,b))

a1 = np.arange(6).reshape(2,3)
b1 = np.arange(6).reshape(2,3)
print(np.append(a1,b1,axis=1))
print(np.append(a1,b1,axis=0))

b2 = np.array([[7,8,9]])
print(np.concatenate((a1,b2), axis=0))



[1 2 3 4 5 6]
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]
[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]
 [7 8 9]]


##### numpy 批量处理

1）得到数据集
2）随机打乱数据
3）定义批大小
4）批处理数据集


In [85]:
data_train = np.random.randn(10000,2,3)
print(len(data_train))

# 打乱
np.random.shuffle(data_train)
batch_size = 100
for i in range(0,len(data_train),batch_size):
    x_batch_sum = np.sum(data_train[i:i+batch_size])

10000


##### numpy 内置函数

In [87]:
import time

x1 = np.random.rand(1000000)
x2 = np.random.rand(1000000)
print(x1)
tic = time.process_time()

dot = 0
for i in range(len(x1)):
    dot+=x1[i]*x2[i]

print(str(dot))
print(np.dot(x1,x2))
    


[0.01505591 0.20119242 0.33375669 ... 0.53164634 0.10384656 0.60954045]
250155.62792099643
250155.62792098479
